### ISSUE TITLE
Start problem 

### ISSUE THREAD

**Issue by vvostokov** [shamhi/YesCoinBot#14]
(venv) PS C:\Users\Admin\PycharmProjects\StavkaTG\YesCoinBot> python main.py
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\StavkaTG\YesCoinBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\Admin\PycharmProjects\StavkaTG\YesCoinBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\Admin\PycharmProjects\StavkaTG\YesCoinBot\bot\utils\launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "C:\Users\Admin\PycharmProjects\StavkaTG\YesCoinBot\venv\lib\site-packages\better_proxy\__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "C:\Users\Admin\PycharmProjects\StavkaTG\YesCoinBot\venv\lib\site-packages\better_proxy\proxy.py", line 16, in <module>
    def _load_lines(filepath: Path | str) -> list[str]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by shamhi** [comment]
use 3.10 or 3.11
