### ISSUE TITLE
не активируется venv

### ISSUE THREAD

**Issue by AnthonyJonson** [shamhi/YesCoinBot#28]
не активируется venv, чтобы я не делал, помогите
![image](https://github.com/shamhi/YesCoinBot/assets/172079674/f224ae77-386a-4aa8-b548-151f14d6a72f)

**Comment by A-platinum** [comment]
Оно и не должно ничего писать, просто продолжай дальше 

venv\Scripts\activate
pip install -r requirements.txt
copy .env-example .env
# Указываете ваши API_ID и API_HASH
python main.py

**Comment by AnthonyJonson** [comment]
![image](https://github.com/shamhi/YesCoinBot/assets/172079674/2573f61a-a020-44a0-8aaa-449cbbc8bd66)

**Comment by Bender-V** [comment]
> Оно и не должно ничего писать, просто продолжай дальше
> 
> venv\Scripts\activate pip install -r requirements.txt copy .env-example .env
> 
> # Указываете ваши API_ID и API_HASH
> python main.py

Как вести?
#API_ID=ххх API_HASH=ххх
у меня не получается

и еще вот такую ошибку выдает
C:\YesCoinBot-main>python main.py
Traceback (most recent call last):
  File "C:\YesCoinBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\YesCoinBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\YesCoinBot-main\bot\utils\launcher.py", line 8, in <module>
    from better_proxy import Proxy
ModuleNotFoundError: No module named 'better_proxy'
