### ISSUE TITLE
AttributeError: 'BadMsgNotification' object has no attribute 'type'

### ISSUE THREAD

**Issue by ehhramaaa** [shamhi/YesCoinBot#7]
Traceback (most recent call last):
  File "N:\Coding\python\YesCoinBot\test.py", line 22, in <module>
    with app:
  File "N:\Coding\python\YesCoinBot\venv\lib\site-packages\pyrogram\client.py", line 302, in __enter__
    return self.start()
  File "N:\Coding\python\YesCoinBot\venv\lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "N:\Coding\python\YesCoinBot\venv\lib\site-packages\pyrogram\methods\utilities\start.py", line 62, in start
    await self.authorize()
  File "N:\Coding\python\YesCoinBot\venv\lib\site-packages\pyrogram\client.py", line 359, in authorize
    sent_code = await self.send_code(self.phone_number)
  File "N:\Coding\python\YesCoinBot\venv\lib\site-packages\pyrogram\methods\auth\send_code.py", line 79, in send_code
    return types.SentCode._parse(r)
  File "N:\Coding\python\YesCoinBot\venv\lib\site-packages\pyrogram\types\authorization\sent_code.py", line 58, in _parse
    type=enums.SentCodeType(type(sent_code.type)),
AttributeError: 'BadMsgNotification' object has no attribute 'type'

Excuseme Sir, Is this due to the difference in my device's time or what?

**Comment by ehhramaaa** [comment]
{
    "_": "types.BadMsgNotification",
    "bad_msg_id": 7368329039842377732,
    "bad_msg_seqno": 5,
    "error_code": 17
}

I printed out send_code and the output same error code 17
